#!/usr/bin/env python3
"""Utility helpers for analysing visdriver debug-trace logs.

This parser focuses on the output generated by
``generate-verification-data`` when the debug trace subsystem is
enabled.  The log format is intentionally textual and fairly regular,
so we perform light-weight parsing using regular expressions rather
than introducing a full parser generator dependency.
"""

from __future__ import annotations

import argparse
import json
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Sequence, Tuple


EXPECTED_HOOKS: Tuple[Tuple[str, str], ...] = (
    ("user32.dll", "CreateWindowExW"),
    ("user32.dll", "CreateWindowExA"),
    ("user32.dll", "DestroyWindow"),
    ("user32.dll", "GetDC"),
    ("user32.dll", "GetDCEx"),
    ("user32.dll", "GetWindowDC"),
    ("user32.dll", "ReleaseDC"),
    ("user32.dll", "BeginPaint"),
    ("user32.dll", "EndPaint"),
    ("gdi32.dll", "CreateCompatibleDC"),
    ("gdi32.dll", "DeleteDC"),
    ("gdi32.dll", "CreateCompatibleBitmap"),
    ("gdi32.dll", "CreateDIBSection"),
    ("gdi32.dll", "DeleteObject"),
    ("gdi32.dll", "SelectObject"),
    ("gdi32.dll", "BitBlt"),
    ("gdi32.dll", "StretchBlt"),
    ("gdi32.dll", "PatBlt"),
    ("gdi32.dll", "SwapBuffers"),
    ("gdi32.dll", "ChoosePixelFormat"),
    ("gdi32.dll", "SetPixelFormat"),
    ("gdi32.dll", "DescribePixelFormat"),
    ("opengl32.dll", "wglCreateContext"),
    ("opengl32.dll", "wglMakeCurrent"),
    ("opengl32.dll", "wglDeleteContext"),
)


HOOK_INSTALL_RE = re.compile(
    r"Installed\s+(?P<count>\d+)\s+debug hooks\s+for\s+(?P<module>[^\s]+)", re.IGNORECASE
)
HOOK_LINE_RE = re.compile(r"hook:\s*(?P<entry>[^\s]+)")
RENDER_OPTIONS_RE = re.compile(
    r"Render options:\s*(?P<width>\d+)x(?P<height>\d+)\s*@\s*(?P<fps>\d+)\s*FPS\s*for\s*(?P<frames>\d+)\s*frames",
    re.IGNORECASE,
)
LOADED_WAV_RE = re.compile(r"Loaded WAV '(?P<path>[^']+)'", re.IGNORECASE)
RUNTIME_DIR_RE = re.compile(r"Runtime directory:\s*(?P<path>.+)$", re.IGNORECASE)
SET_CWD_RE = re.compile(r"SetCurrentDirectory to (?P<path>.+)$", re.IGNORECASE)
WINDOW_RE = re.compile(
    r"^CreateWindowEx(?P<ansi>[WA])\s+class=(?P<class>\S+)\s+name=(?P<name>.*?)\s+ex=0x(?P<ex>[0-9A-Fa-f]{8})\s+style=0x(?P<style>[0-9A-Fa-f]{8})\s+parent=(?P<parent>\S+)",
)
FRAME_BEGIN_RE = re.compile(r"^Frame\s+(?P<frame>\d+):\s+begin$", re.IGNORECASE)


@dataclass
class WindowInfo:
    index: int
    ansi_variant: str
    class_name: str
    title: str
    ex_style: str
    style: str
    parent: str
    line_no: int


@dataclass
class HookInfo:
    dll: str
    function: str
    seen_in_log: bool = False
    invocation_lines: List[int] = field(default_factory=list)


@dataclass
class TraceSummary:
    hook_install_count: Optional[int]
    hooks: Dict[str, HookInfo]
    render_width: Optional[int]
    render_height: Optional[int]
    render_fps: Optional[int]
    render_frame_count: Optional[int]
    wav_path: Optional[str]
    runtime_directory: Optional[str]
    windows: List[WindowInfo]
    frame_events: List[int]

    def to_dict(self) -> Dict[str, object]:
        return {
            "hook_install_count": self.hook_install_count,
            "hooks": {
                name: {
                    "dll": info.dll,
                    "function": info.function,
                    "seen_in_log": info.seen_in_log,
                    "invocation_lines": info.invocation_lines,
                }
                for name, info in sorted(self.hooks.items())
            },
            "render": {
                "width": self.render_width,
                "height": self.render_height,
                "fps": self.render_fps,
                "frames": self.render_frame_count,
            },
            "wav_path": self.wav_path,
            "runtime_directory": self.runtime_directory,
            "windows": [
                {
                    "index": win.index,
                    "variant": win.ansi_variant,
                    "class": win.class_name,
                    "title": win.title,
                    "ex_style": win.ex_style,
                    "style": win.style,
                    "parent": win.parent,
                    "line": win.line_no,
                }
                for win in self.windows
            ],
            "frame_events": self.frame_events,
        }


def _prepare_expected_hooks() -> Dict[str, HookInfo]:
    hooks: Dict[str, HookInfo] = {}
    for dll, function in EXPECTED_HOOKS:
        key = f"{dll}!{function}"
        hooks[key] = HookInfo(dll=dll, function=function)
    return hooks


def parse_trace(log_path: Path) -> TraceSummary:
    text = log_path.read_text(encoding="utf-8-sig", errors="replace")
    lines = text.splitlines()

    hooks = _prepare_expected_hooks()
    hook_install_count: Optional[int] = None
    render_width = render_height = render_fps = render_frame_count = None
    wav_path: Optional[str] = None
    runtime_directory: Optional[str] = None
    windows: List[WindowInfo] = []
    frame_events: List[int] = []

    hook_iteration_active = False
    hook_iteration_names: List[str] = []

    invocation_patterns: Dict[str, re.Pattern[str]] = {}
    for info in hooks.values():
        invocation_patterns[info.function] = re.compile(
            rf"\b{re.escape(info.function)}\b", re.IGNORECASE
        )

    for idx, line in enumerate(lines):
        line_no = idx + 1

        install_match = HOOK_INSTALL_RE.search(line)
        if install_match:
            hook_install_count = int(install_match.group("count"))
            hook_iteration_active = True
            hook_iteration_names.clear()
            continue

        if hook_iteration_active:
            hook_match = HOOK_LINE_RE.search(line)
            if hook_match:
                hook_entry = hook_match.group("entry").strip()
                hook_iteration_names.append(hook_entry)
                if hook_entry in hooks:
                    # Keep track of the order they were declared in the log.
                    pass
                else:
                    hooks.setdefault(
                        hook_entry,
                        HookInfo(dll=hook_entry.split("!")[0], function=hook_entry.split("!")[1]),
                    )
                continue
            else:
                hook_iteration_active = False

        if render_width is None:
            render_match = RENDER_OPTIONS_RE.search(line)
            if render_match:
                render_width = int(render_match.group("width"))
                render_height = int(render_match.group("height"))
                render_fps = int(render_match.group("fps"))
                render_frame_count = int(render_match.group("frames"))
                continue

        if wav_path is None:
            wav_match = LOADED_WAV_RE.search(line)
            if wav_match:
                wav_path = wav_match.group("path")
                continue

        runtime_match = RUNTIME_DIR_RE.search(line)
        if runtime_match:
            runtime_directory = runtime_match.group("path")
            continue

        if runtime_directory is None:
            setcwd_match = SET_CWD_RE.search(line)
            if setcwd_match:
                runtime_directory = setcwd_match.group("path")

        window_match = WINDOW_RE.search(line)
        if window_match:
            windows.append(
                WindowInfo(
                    index=len(windows),
                    ansi_variant=window_match.group("ansi"),
                    class_name=window_match.group("class"),
                    title=window_match.group("name"),
                    ex_style=f"0x{window_match.group('ex').upper()}",
                    style=f"0x{window_match.group('style').upper()}",
                    parent=window_match.group("parent"),
                    line_no=line_no,
                )
            )
            continue

        frame_match = FRAME_BEGIN_RE.match(line)
        if frame_match:
            frame_events.append(int(frame_match.group("frame")))

        if "hook:" in line:
            continue

        for key, pattern in invocation_patterns.items():
            if pattern.search(line):
                hook_key = None
                for name, info in hooks.items():
                    if info.function.lower() == key.lower():
                        hook_key = name
                        break
                if hook_key is None:
                    continue
                hooks[hook_key].seen_in_log = True
                hooks[hook_key].invocation_lines.append(line_no)

    return TraceSummary(
        hook_install_count=hook_install_count,
        hooks=hooks,
        render_width=render_width,
        render_height=render_height,
        render_fps=render_fps,
        render_frame_count=render_frame_count,
        wav_path=wav_path,
        runtime_directory=runtime_directory,
        windows=windows,
        frame_events=frame_events,
    )


def describe_summary(summary: TraceSummary) -> str:
    lines: List[str] = []

    if summary.hook_install_count is not None:
        lines.append(
            f"Hook install count: {summary.hook_install_count} (expected {len(EXPECTED_HOOKS)})"
        )
    else:
        lines.append("Hook install count: not found")

    missing_hooks = [name for name in expected_hook_names() if name not in summary.hooks]
    if missing_hooks:
        lines.append("Missing hook declarations: " + ", ".join(sorted(missing_hooks)))

    unseen_hooks = [
        name for name, info in summary.hooks.items() if not info.seen_in_log and name in expected_hook_names()
    ]
    if unseen_hooks:
        lines.append("Hooks not invoked in trace: " + ", ".join(sorted(unseen_hooks)))

    if summary.render_width and summary.render_height:
        lines.append(
            f"Render target: {summary.render_width}x{summary.render_height} @ {summary.render_fps} FPS for {summary.render_frame_count} frames"
        )

    if summary.wav_path:
        lines.append(f"Loaded WAV: {summary.wav_path}")

    if summary.runtime_directory:
        lines.append(f"Runtime directory: {summary.runtime_directory}")

    if summary.windows:
        lines.append("Window creations:")
        for win in summary.windows:
            lines.append(
                f"  [{win.index}] CreateWindowEx{win.ansi_variant} class={win.class_name} name={win.title} ex={win.ex_style} style={win.style} parent={win.parent}"
            )

    if summary.frame_events:
        lines.append(
            f"Frames logged: {len(summary.frame_events)} unique entries (min={min(summary.frame_events)}, max={max(summary.frame_events)})"
        )

    return "\n".join(lines)


def expected_hook_names() -> List[str]:
    return [f"{dll}!{func}" for dll, func in EXPECTED_HOOKS]


def _parse_args(argv: Optional[Sequence[str]] = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Analyse visdriver debug trace logs")
    parser.add_argument("log", type=Path, help="Path to the debug trace log")
    parser.add_argument(
        "--json",
        action="store_true",
        help="Emit a JSON summary instead of the human readable report",
    )
    return parser.parse_args(argv)


def main(argv: Optional[Sequence[str]] = None) -> int:
    args = _parse_args(argv)
    summary = parse_trace(args.log)

    if args.json:
        print(json.dumps(summary.to_dict(), indent=2))
    else:
        print(describe_summary(summary))

    return 0


if __name__ == "__main__":
    raise SystemExit(main())

